-- 20260321131500_init
-- +migrate Down
-- +migrate Dialect postgres

DROP TABLE IF EXISTS words CASCADE;
DROP TABLE IF EXISTS word_group_conflicts CASCADE;
DROP TABLE IF EXISTS user_selected_models CASCADE;
DROP TABLE IF EXISTS user_personalization_settings CASCADE;
DROP TABLE IF EXISTS user_model_providers CASCADE;
DROP TABLE IF EXISTS user_model_provider_groups CASCADE;
DROP TABLE IF EXISTS user_model_provider_group_models CASCADE;
DROP TABLE IF EXISTS uploaded_files CASCADE;
DROP TABLE IF EXISTS upload_sessions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS system_user_preferences CASCADE;
DROP TABLE IF EXISTS system_memories CASCADE;
DROP TABLE IF EXISTS skill_share_tasks CASCADE;
DROP TABLE IF EXISTS skill_share_items CASCADE;
DROP TABLE IF EXISTS skill_resources CASCADE;
DROP TABLE IF EXISTS resource_suggestions CASCADE;
DROP TABLE IF EXISTS resource_session_snapshots CASCADE;
DROP TABLE IF EXISTS prompts CASCADE;
DROP TABLE IF EXISTS multi_answers_switches CASCADE;
DROP TABLE IF EXISTS multi_answers_chat_histories CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS default_prompts CASCADE;
DROP TABLE IF EXISTS default_models CASCADE;
DROP TABLE IF EXISTS default_model_providers CASCADE;
DROP TABLE IF EXISTS default_datasets CASCADE;
DROP TABLE IF EXISTS datasets CASCADE;
DROP TABLE IF EXISTS dataset_members CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS chat_histories CASCADE;
DROP TABLE IF EXISTS agent_user_active_threads CASCADE;
DROP TABLE IF EXISTS agent_threads CASCADE;
DROP TABLE IF EXISTS agent_thread_rounds CASCADE;
DROP TABLE IF EXISTS agent_thread_records CASCADE;
DROP TABLE IF EXISTS acl_visibility CASCADE;
DROP TABLE IF EXISTS acl_user_groups CASCADE;
DROP TABLE IF EXISTS acl_rows CASCADE;
DROP TABLE IF EXISTS acl_kbs CASCADE;
DROP TABLE IF EXISTS acl_groups CASCADE;

-- +migrate Dialect sqlite
DROP INDEX IF EXISTS "idx_acl_resource";
DROP INDEX IF EXISTS "idx_acl_visibility_resource_id";
DROP INDEX IF EXISTS "idx_agent_thread_records_round_stream_id";
DROP INDEX IF EXISTS "idx_agent_thread_records_task_id";
DROP INDEX IF EXISTS "idx_agent_thread_records_thread_round_id";
DROP INDEX IF EXISTS "idx_agent_thread_records_thread_stream_id";
DROP INDEX IF EXISTS "idx_agent_thread_rounds_task_id";
DROP INDEX IF EXISTS "idx_agent_thread_rounds_thread_id";
DROP INDEX IF EXISTS "idx_agent_thread_rounds_thread_request_hash";
DROP INDEX IF EXISTS "idx_agent_threads_current_task_id";
DROP INDEX IF EXISTS "idx_agent_user_active_threads_status_lease";
DROP INDEX IF EXISTS "idx_agent_user_active_threads_thread_id";
DROP INDEX IF EXISTS "idx_chat_histories_conversation_id";
DROP INDEX IF EXISTS "idx_datasets_kb_id";
DROP INDEX IF EXISTS "idx_documents_dataset_id";
DROP INDEX IF EXISTS "idx_documents_lazyllm_doc_id";
DROP INDEX IF EXISTS "idx_documents_p_id";
DROP INDEX IF EXISTS "idx_multi_answers_chat_histories_conversation_id";
DROP INDEX IF EXISTS "idx_resource_session_snapshots_session_id";
DROP INDEX IF EXISTS "idx_resource_suggestions_list";
DROP INDEX IF EXISTS "idx_resource_suggestions_session_id";
DROP INDEX IF EXISTS "idx_resource_uid";
DROP INDEX IF EXISTS "idx_skill_resources_owner_node_enabled";
DROP INDEX IF EXISTS "idx_skill_share_items_target_user";
DROP INDEX IF EXISTS "idx_skill_share_tasks_source_user";
DROP INDEX IF EXISTS "idx_tasks_algo_id";
DROP INDEX IF EXISTS "idx_tasks_dataset_id";
DROP INDEX IF EXISTS "idx_tasks_doc_id";
DROP INDEX IF EXISTS "idx_tasks_document_p_id";
DROP INDEX IF EXISTS "idx_tasks_kb_id";
DROP INDEX IF EXISTS "idx_tasks_lazyllm_task_id";
DROP INDEX IF EXISTS "idx_tasks_target_dataset_id";
DROP INDEX IF EXISTS "idx_tasks_task_type";
DROP INDEX IF EXISTS "idx_upload_sessions_dataset_id";
DROP INDEX IF EXISTS "idx_upload_sessions_document_id";
DROP INDEX IF EXISTS "idx_upload_sessions_task_id";
DROP INDEX IF EXISTS "idx_upload_sessions_tenant_id";
DROP INDEX IF EXISTS "idx_upload_sessions_upload_id";
DROP INDEX IF EXISTS "idx_upload_sessions_upload_state";
DROP INDEX IF EXISTS "idx_uploaded_files_dataset_id";
DROP INDEX IF EXISTS "idx_uploaded_files_document_id";
DROP INDEX IF EXISTS "idx_uploaded_files_status";
DROP INDEX IF EXISTS "idx_uploaded_files_task_id";
DROP INDEX IF EXISTS "idx_uploaded_files_tenant_id";
DROP INDEX IF EXISTS "idx_uploaded_files_upload_file_id";
DROP INDEX IF EXISTS "idx_user_model_provider_group_models_provider";
DROP INDEX IF EXISTS "idx_user_model_provider_groups_parent";
DROP INDEX IF EXISTS "idx_word_column";
DROP INDEX IF EXISTS "idx_word_create_user_group_id";
DROP INDEX IF EXISTS "idx_word_group_conflict_user_updated";
DROP INDEX IF EXISTS "uk_agent_thread_records_record_key";
DROP INDEX IF EXISTS "uk_default_model_providers_name";
DROP INDEX IF EXISTS "uk_default_models_provider_name";
DROP INDEX IF EXISTS "uk_resource_session_snapshots";
DROP INDEX IF EXISTS "uk_skill_resources_owner_relative_path";
DROP INDEX IF EXISTS "uk_system_memories_user_id";
DROP INDEX IF EXISTS "uk_system_user_preferences_user_id";
DROP INDEX IF EXISTS "uk_user_model_provider_group_models_group_name";
DROP INDEX IF EXISTS "uk_user_personalization_settings_user_id";
DROP INDEX IF EXISTS "uk_user_selected_models_user_type";
DROP INDEX IF EXISTS "ukx_create_user_id_dataset_id";
DROP TABLE IF EXISTS "acl_groups";
DROP TABLE IF EXISTS "acl_kbs";
DROP TABLE IF EXISTS "acl_rows";
DROP TABLE IF EXISTS "acl_user_groups";
DROP TABLE IF EXISTS "acl_visibility";
DROP TABLE IF EXISTS "agent_thread_records";
DROP TABLE IF EXISTS "agent_thread_rounds";
DROP TABLE IF EXISTS "agent_threads";
DROP TABLE IF EXISTS "agent_user_active_threads";
DROP TABLE IF EXISTS "chat_histories";
DROP TABLE IF EXISTS "conversations";
DROP TABLE IF EXISTS "datasets";
DROP TABLE IF EXISTS "default_datasets";
DROP TABLE IF EXISTS "default_model_providers";
DROP TABLE IF EXISTS "default_models";
DROP TABLE IF EXISTS "default_prompts";
DROP TABLE IF EXISTS "documents";
DROP TABLE IF EXISTS "multi_answers_chat_histories";
DROP TABLE IF EXISTS "multi_answers_switches";
DROP TABLE IF EXISTS "prompts";
DROP TABLE IF EXISTS "resource_session_snapshots";
DROP TABLE IF EXISTS "resource_suggestions";
DROP TABLE IF EXISTS "skill_resources";
DROP TABLE IF EXISTS "skill_share_items";
DROP TABLE IF EXISTS "skill_share_tasks";
DROP TABLE IF EXISTS "system_memories";
DROP TABLE IF EXISTS "system_user_preferences";
DROP TABLE IF EXISTS "tasks";
DROP TABLE IF EXISTS "upload_sessions";
DROP TABLE IF EXISTS "uploaded_files";
DROP TABLE IF EXISTS "user_model_provider_group_models";
DROP TABLE IF EXISTS "user_model_provider_groups";
DROP TABLE IF EXISTS "user_model_providers";
DROP TABLE IF EXISTS "user_personalization_settings";
DROP TABLE IF EXISTS "user_selected_models";
DROP TABLE IF EXISTS "word_group_conflicts";
DROP TABLE IF EXISTS "words";
